version: '3'
services:
 mongodb:
   image: mongo
   ports:
     - "27017:27017"
   container_name: mongo2
   network_mode: host
 muzixapp:
   image: trackservice
   build: userservice/
   restart: always
   container_name: trackservice2
   network_mode: host
   ports:
     - "8080:8080"
   expose:
     - 8080
